### ISSUE TITLE
Create tree data structure

### ISSUE THREAD

**Issue by orozco92** [easygrating/easytree#1]
Create the Tree class

Avaliable methods:

- [x] addChild
- [x] removeChild
- [x] findChild
- [x] toList
- [x] toListIds
- [x] getChildList

> It must be written in Typescript. We need to use abstract clases, interfaces and types

All methods are just the same as in tree utility at suite-api
Write test cases for each one

**Comment by nacastroc** [comment]
@orozco92 I have a question: Should the `addChild` and `removeChild` now include both an update of the `_parent` reference and also check that, on adding a child, there is no other child with the same id already on the tree?

<img width="843" title="Old and new tree utility sid-by-side" alt="Old and new tree utility sid-by-side" src="https://user-images.githubusercontent.com/29256804/223312466-3b8edc46-d750-4e94-9d01-f11c725bb568.png">
